apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-app-simulator-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: driver-app-simulator
  template:
    metadata:
      labels:
        app: driver-app-simulator
    spec:
      containers:
        - name: driver-app-simulator-container
          image: ${IMAGE_NAME}:${IMAGE_TAG::7}
          ports:
            - containerPort: 8080