apiVersion: v1
kind: Service
metadata:
  name: driver-app-simulator-service
spec:
  type: LoadBalancer
  selector:
    app: driver-app-simulator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080